### ISSUE TITLE
Question about Bentley-Ottmann algorithm.

### ISSUE THREAD

**Issue by mithi** [volfegan/GeometricAlgorithms#1]
Hi Daniel!

I came across your repository, and it's amazing! Thank you for putting this out there and even adding a detailed discussion. 

I'm currently writing an extremely lightweight graphics engine which you can use to project 3d points, lines, and planes in a 2d SVG. Here's the [demo](https://mithi.github.io/hello-3d-world/) where you can play with the parameters and here's the actual [source code](https://github.com/mithi/bare-minimum-3d)

It's almost done, but one or the core features that is not yet implemented is hidden points / lines / surface removal. I know nobody wants to spend time doing something they're not interested in for free, but if this is something that excites you, I'd gladly  credit you as a main contributor, if you wish to help in whatever way you think is best.

Thanks again for taking the time to read my message! Would really love to hear your thoughts.

**Comment by volfegan** [comment]
That is some very nice project you did there. I always try to avoid 3D stuff. Too hard. It seems I can't even finish even my own stuff. You see, that Spatial Hashing Collision system posted is incomplete, but I already have the finished package. I just didn't like the results and to upload the complete version, the reasons why is not good are so meddlesome. Who has time for that?

Sure it is unexpected someone actually gave a look at my toy studies. Maybe I should finish that and give a proper closure.

I'm sorry to decline your offer. In case you use Twitter (https://twitter.com/VolfeganGeist), you can ask me questions there. I follow some really good programmers. Maybe one of them has interesting in your project. Who knows if it is not what they need right now...

I wish you the best of luck in your endeavors.
Volfegan

**Comment by mithi** [comment]
@volfegan thank you for taking the time to reply! All the best!
